from enum import Enum


class CustomerAccessibility(Enum):
    """Enumeration for a customer's accessibility requirements.

    - :CUSTOMER_ACCESSIBILITY_UNKNOWN:
    - :CUSTOMER_ACCESSIBILITY_AUDIO:
    - :CUSTOMER_ACCESSIBILITY_LARGE_PRINT:
    - :CUSTOMER_ACCESSIBILITY_BRAILLE:
    - :CUSTOMER_ACCESSIBILITY_DEAF:
    """
    CUSTOMER_ACCESSIBILITY_UNKNOWN = 'CUSTOMER_ACCESSIBILITY_UNKNOWN'
    CUSTOMER_ACCESSIBILITY_AUDIO = 'CUSTOMER_ACCESSIBILITY_AUDIO'
    CUSTOMER_ACCESSIBILITY_LARGE_PRINT = 'CUSTOMER_ACCESSIBILITY_LARGE_PRINT'
    CUSTOMER_ACCESSIBILITY_BRAILLE = 'CUSTOMER_ACCESSIBILITY_BRAILLE'
    CUSTOMER_ACCESSIBILITY_DEAF = 'CUSTOMER_ACCESSIBILITY_DEAF'


class CustomerContactMethod(Enum):
    """Enumeration for a customer's preferred method of contact.

    - :CUSTOMER_CONTACT_METHOD_UNKNOWN:
    - :CUSTOMER_CONTACT_METHOD_NONE:
    - :CUSTOMER_CONTACT_METHOD_EMAIL:
    - :CUSTOMER_CONTACT_METHOD_SMS:
    - :CUSTOMER_CONTACT_METHOD_NOTIFICATION:
    """
    CUSTOMER_TITLE_UNKNOWN = 'CUSTOMER_CONTACT_METHOD_UNKNOWN'
    CUSTOMER_CONTACT_METHOD_NONE = 'CUSTOMER_CONTACT_METHOD_NONE'
    CUSTOMER_CONTACT_METHOD_EMAIL = 'CUSTOMER_CONTACT_METHOD_EMAIL'
    CUSTOMER_CONTACT_METHOD_SMS = 'CUSTOMER_CONTACT_METHOD_SMS'
    CUSTOMER_CONTACT_METHOD_NOTIFICATION = \
        'CUSTOMER_CONTACT_METHOD_NOTIFICATION'


class CustomerGender(Enum):
    """Enumeration for a customer's gender.

    - :CUSTOMER_GENDER_UNKNOWN:
    - :CUSTOMER_GENDER_FEMALE:
    - :CUSTOMER_GENDER_MALE:
    """
    CUSTOMER_GENDER_UNKNOWN = 'CUSTOMER_GENDER_UNKNOWN'
    CUSTOMER_GENDER_FEMALE = 'CUSTOMER_GENDER_FEMALE'
    CUSTOMER_GENDER_MALE = 'CUSTOMER_GENDER_MALE'


class CustomerTitle(Enum):
    """Enumeration for a customer's title.

    - :CUSTOMER_TITLE_UNKNOWN:
    - :CUSTOMER_TITLE_MISS:
    - :CUSTOMER_TITLE_MR:
    - :CUSTOMER_TITLE_MRS:
    - :CUSTOMER_TITLE_MS:
    """
    CUSTOMER_TITLE_UNKNOWN = 'CUSTOMER_TITLE_UNKNOWN'
    CUSTOMER_TITLE_MISS = 'CUSTOMER_TITLE_MISS'
    CUSTOMER_TITLE_MR = 'CUSTOMER_TITLE_MR'
    CUSTOMER_TITLE_MRS = 'CUSTOMER_TITLE_MRS'
    CUSTOMER_TITLE_MS = 'CUSTOMER_TITLE_MS'
