from enum import Enum


class PostingPhase(Enum):
    """The phase of a posting.

    - :POSTING_PHASE_UNKNOWN:
    - :POSTING_PHASE_PENDING_INCOMING:
    - :POSTING_PHASE_PENDING_OUTGOING:
    - :POSTING_PHASE_COMMITTED:
    """
    POSTING_PHASE_UNKNOWN = 'POSTING_PHASE_UNKNOWN'
    POSTING_PHASE_PENDING_INCOMING = 'POSTING_PHASE_PENDING_INCOMING'
    POSTING_PHASE_PENDING_OUTGOING = 'POSTING_PHASE_PENDING_OUTGOING'
    POSTING_PHASE_COMMITTED = 'POSTING_PHASE_COMMITTED'
