from enum import Enum


class TransactionStatus(Enum):
    """Enumeration for the status of a Transaction.

    - :TRANSACTION_STATUS_UNKNOWN:
    - :TRANSACTION_STATUS_PENDING:
    - :TRANSACTION_STATUS_BOOKED:
    - :TRANSACTION_STATUS_REJECTED:
    """
    TRANSACTION_STATUS_UNKNOWN = "TRANSACTION_STATUS_UNKNOWN"
    TRANSACTION_STATUS_PENDING = "TRANSACTION_STATUS_PENDING"
    TRANSACTION_STATUS_BOOKED = "TRANSACTION_STATUS_BOOKED"
    TRANSACTION_STATUS_REJECTED = "TRANSACTION_STATUS_REJECTED"


class ChargeAmountAsset(Enum):
    """Enumeration for the asset type of the denomination for a Charge Amount.

    - :UNKNOWN:
    - :CASH:
    """
    UNKNOWN = 'UNKNOWN'
    CASH = 'CASH'


class TransactionRejectionCode(Enum):
    """Enumeration for the rejection code of a Transaction.

    If a transaction has status rejected, this code represents the reason for
    being rejected.

    - :REJECTION_CODE_UNKNOWN:
    - :REJECTION_CODE_INSUFFICIENT_FUNDS:
    - :REJECTION_CODE_CREDITOR:
    - :REJECTION_CODE_DEBITOR:
    - :REJECTION_CODE_INVALID_DENOMINATION:
    - :REJECTION_CODE_INVALID_AMOUNT:
    - :REJECTION_CODE_EXTERNAL:
    """
    REJECTION_CODE_UNKNOWN = "REJECTION_CODE_UNKNOWN"
    REJECTION_CODE_INSUFFICIENT_FUNDS = "REJECTION_CODE_INSUFFICIENT_FUNDS"
    REJECTION_CODE_CREDITOR = "REJECTION_CODE_CREDITOR"
    REJECTION_CODE_DEBITOR = "REJECTION_CODE_DEBITOR"
    REJECTION_CODE_INVALID_DENOMINATION = "REJECTION_CODE_INVALID_DENOMINATION"
    REJECTION_CODE_INVALID_AMOUNT = "REJECTION_CODE_INVALID_AMOUNT"
    REJECTION_CODE_EXTERNAL = "REJECTION_CODE_EXTERNAL"


class TransactionEventType(Enum):
    """Enumeration for the type of a TransactionEvent.

    This code represents whether the event was a create or update event.

    - :TRANSACTION_EVENT_UNKNOWN:
    - :TRANSACTION_EVENT_CREATED:
    - :TRANSACTION_EVENT_UPDATED:
    """
    TRANSACTION_EVENT_UNKNOWN = "TRANSACTION_EVENT_UNKNOWN"
    TRANSACTION_EVENT_CREATED = "TRANSACTION_EVENT_CREATED"
    TRANSACTION_EVENT_UPDATED = "TRANSACTION_EVENT_UPDATED"


class TransactionDirection(Enum):
    """Enumeration for the Direction of a Transaction.

    This enum is exclusively used by the
    `list_transactions` functions
    within :class:`tmvault.rest_api.TransactionsAPI`.

    - :TRANSACTION_DIRECTION_ALL:
    - :TRANSACTION_DIRECTION_CREDIT:
    - :TRANSACTION_DIRECTION_DEBIT:
    """
    TRANSACTION_DIRECTION_ALL = "TRANSACTION_DIRECTION_ALL"
    TRANSACTION_DIRECTION_CREDIT = "TRANSACTION_DIRECTION_CREDIT"
    TRANSACTION_DIRECTION_DEBIT = "TRANSACTION_DIRECTION_DEBIT"


class TransactionOrderBy(Enum):
    """Enumeration for the order by options for the `list_transactions`
    endpoint.

    This enum is exclusively used by the
    `list_transactions` functions
    within :class:`tmvault.rest_api.TransactionsAPI`.

    - :ORDER_BY_LAST_UPDATE_TIMESTAMP_DESC:
    - :ORDER_BY_LAST_UPDATE_TIMESTAMP_ASC:
    - :ORDER_BY_CHARGE_AMOUNT_DENOMINATION_DESC:
    - :ORDER_BY_CHARGE_AMOUNT_DENOMINATION_ASC:
    - :ORDER_BY_REFERENCE_DESC:
    - :ORDER_BY_REFERENCE_ASC:
    - :ORDER_BY_VALUE_TIMESTAMP_DESC:
    - :ORDER_BY_VALUE_TIMESTAMP_ASC:
    - :ORDER_BY_BOOKING_TIMESTAMP_DESC:
    - :ORDER_BY_BOOKING_TIMESTAMP_ASC:
    - :ORDER_BY_CHARGE_AMOUNT_VALUE_DESC:
    - :ORDER_BY_CHARGE_AMOUNT_VALUE_ASC:
    """
    ORDER_BY_LAST_UPDATE_TIMESTAMP_DESC = "ORDER_BY_LAST_UPDATE_TIMESTAMP_DESC"
    ORDER_BY_LAST_UPDATE_TIMESTAMP_ASC = "ORDER_BY_LAST_UPDATE_TIMESTAMP_ASC"
    ORDER_BY_CHARGE_AMOUNT_DENOMINATION_DESC = (
        "ORDER_BY_CHARGE_AMOUNT_DENOMINATION_DESC"
    )
    ORDER_BY_CHARGE_AMOUNT_DENOMINATION_ASC = (
        "ORDER_BY_CHARGE_AMOUNT_DENOMINATION_ASC"
    )
    ORDER_BY_REFERENCE_DESC = "ORDER_BY_REFERENCE_DESC"
    ORDER_BY_REFERENCE_ASC = "ORDER_BY_REFERENCE_ASC"
    ORDER_BY_VALUE_TIMESTAMP_DESC = "ORDER_BY_VALUE_TIMESTAMP_DESC"
    ORDER_BY_VALUE_TIMESTAMP_ASC = "ORDER_BY_VALUE_TIMESTAMP_ASC"
    ORDER_BY_BOOKING_TIMESTAMP_DESC = 'ORDER_BY_BOOKING_TIMESTAMP_DESC'
    ORDER_BY_BOOKING_TIMESTAMP_ASC = "ORDER_BY_BOOKING_TIMESTAMP_ASC"
    ORDER_BY_CHARGE_AMOUNT_VALUE_DESC = "ORDER_BY_CHARGE_AMOUNT_VALUE_DESC"
    ORDER_BY_CHARGE_AMOUNT_VALUE_ASC = "ORDER_BY_CHARGE_AMOUNT_VALUE_ASC"
